[alias]
xtask = "run --release --manifest-path ./xtask/Cargo.toml --"

[target.riscv64imac-unknown-none-elf]
rustflags = "-C link-arg=-Trv64.lds -C relocation-model=pic -C link-arg=--pie"
runner = "qemu-system-riscv64 -smp 2 -m 256M -machine virt -nographic -serial mon:stdio -bios fw_jump64.elf -kernel "

# [target.riscv64imac-unknown-none-elf.unstable]
# build-std = ["core", "compiler_builtins"]
# build-std-features = ["compiler-builtins-mem"]
